repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
            language_version: 3.9.16
            args: [-t, py39]
    - repo: https://github.com/hadialqattan/pycln
      rev: v0.0.1-beta.3
      hooks:
          - id: pycln
    - repo: https://github.com/pycqa/isort
      rev: 5.5.4
      hooks:
          - id: isort
            files: "\\.(py)$"
